---
title: "Experience"
output: 
  html_document:
    toc: true
    toc_float: true
---
<center><h1>Teshawna Badu</h1> </center>
<center><h3>New york, NY</h3> </center>
<center><h5>Primary email: tb2910@cumc.columbia.edu</h5> </center>

<center><h1>Profile</h1> </center>
I am currently studying at Columbia University Mailman School of Public Health. I am an MPH candidate in Epidemiology department with a certificate in Applied Biostatistics and Public Health Data Science. 


<center><h1>Education</h1></center>

#### Columbia University, Mailman School of Public Health           - May 2022
 * Master of Public Health
    - Department – Epidemiology 
    - Certificate – Applied Biostatistics and Public Health Data Science 
        
#### CUNY Hunter College                                          - May 2018
 * Bachelor of Arts
    - Major – Biochemistry
    - Minor – Anthropology
    
  
$~$

<center><h1>Employment and Internships</h1></center>   
#### Columbia University Mailman School of Public Health, New York NY                       		 
* Date: September 2021- Present
* Title: Graduate Teaching Assistant for Quantitative Research Methods
  - Facilitating weekly lab sessions explaining statistical concepts and working through problem-sets with over 20 first-year MPH graduate students; holding weekly office hours to communicate course material and provide students’ additional support.
  - Collaborating with faculty to develop weekly lesson plan and rubric for grading assignments
  - Grading students’ homework and assignment; providing feedback and academic support as needed. 

$~$

#### ICAP at Columbia University, New York NY 						                   
* Date: May 2021- Present
* Title: Research Assistant, LeCellPHIA team
  - Perform data cleaning, wrangling, and analysis of over 130,000 observations in SAS to monitoring and assure data quality of a longitudinal, high-frequency COVID-19 surveillance system: Lesotho Cellphone Population-Based HIV Impact Assessment (LeCellPHIA) study.
  - Lead design of monitoring tool for supervisors to ensure quality assurance and quality control of the study.
  - Prepare protocol; conduct structured in-depth qualitative interviews with LeCellPHIA interviewers to examine interviewer effects and develop best practices for cellphone surveillance research in low and middle-income countries.

$~$

#### Correlation One, New York NY									    
* Date: April 2021- August 2021
* Title: Data Science for All (DS4A) Fellow 
  - Admitted into a merit-based fellowship in Data Analytics & Artificial Intelligence with less than 5% acceptance rate to learn Data Science.
  - Utilized Pandas, NumPy, Matplotlib, and Seaborn libraries of Python to analyze case studies and create data visualizations.
  - Developed and presented a final group project entitled “Covid-19 Responsibility Index”; analyzed and created a 5-star rating system for 150 schools from the 5 Boroughs in New York City to assess their performance and actions taken to curb the spread of Covid-19. 
  
$~$

#### Albert Einstein College of Medicine, Bronx NY 						                  
* Date: Nov 2018- March 2020
* Title:Research Trainee, Department of Family & Social Medicine
Awards: NIH Diversity Supplement Awardee (2018)
Project # R03HL140265-01 Title: Housing mobility, hypertension, self-management, and health care utilization among Bronx Latinos.
  - Conducted literature review to assess evidence on the role of residential mobility on chronic disease management. 
  -	Characterized the differences in the housing type and access to social amenities of 300 participants in the Study of Latinos (SOL) cohort living with hypertension using Google Street View.
  -Analyzed data sets using Excel to determine whether living in a less favorable neighborhood is associated with self-rated health. 
  
$~$

#### Albert Einstein College of Medicine, Bronx NY 						                  
* Date :June- August 2017
* Title: Health Career Connection Intern, Department of Family & Social Medicine
  - Identified useful metrics to evaluate the built and social environment to be used in a natural experiment study compiled and used for an R21 under Dr. Earle Chambers. 
  - Conducted a literature review to inform grant R01DK121896, an experimental study of diabetes prevention among men of color; examined the factors that influence participation of men of color in clinical trials and research studies. 
  - Developed an understanding of research design and methodology by reviewing manuscripts submitted for peer review. 
  -Contributed to writing of research grant proposals; prepared manuscripts for submission based on original research.
  
$~$

#### New York Department of Health and Mental Hygiene, Queens NY                                                        
* Date : July 2016-August 2016 
* Title: Health Research Training Program Administrative Intern 
  -	Conducted literature reviews to determine publication status of Epi Scholars Alumni, summarized results in Microsoft Excel.
  - Researched and recorded contact information on 100 Historically Black Colleges and Universities to support the Health Research Training Program’s diversity initiative. 
  -	Prepared a historical overview report of the NYDOHMH funded scholarship program for staff; used administrative data to prepare charts and graphs to depict retention rates and overall cost of the program
  - Redesigned survey tool to measure the impact of the agency’s funded scholarship program using Survey Monkey.
  - Presented research findings and suggested next steps to leadership and staff within the Bureau of Public Health Training.

$~$

<center><h1>Skills</h1></center> 
#### Profecient in the following:
- SAS
- R Studio
- Microsoft Office Suites
  - Word
  - PowerPoint
  - Excel
- SurveyCTO
- Survey Monkey

$~$
$~$
<center><h1>Other Relevant Information</h1></center>
<details>
<summary>Relative Coursework</summary>
<li>Columbia CORE</li>
<li>SAS Course</li></ul>
<li>Epidemiology II & III</li></ul>
<li>Data Science</li></ul>
<li> Spatial Epidemiology </li></ul>
<li> Applied Regression </li></ul>
<li> Analysis of Categorical Data </li></ul>
</details>

$~$

<details>
<summary>Certificates</summary>
<li>CITI- "Collaborative Institutional Training Initiative”</li>
<li>HIPPA- TC0019: “Health Insurance Portability Accountability Act Research Training Course”</li>
<li>Mental Health First Aid</li>
</details>